services: 
  postgres:
    container_name: porcentagem-core-db
    image: bitnami/postgresql
    ports:
      - 5201:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=porcentagem-core
